# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38eb77df3676273d927b1dd69677dc5f7829c38c6bcb05cf6207034b244049d3bd43090f9ba617ea9876acc7523694f4376b9f54771ed3485dd996da943e9d44

test:
  secret_key_base: c412d321349b7566d4b5ff7f08fd249910e0436a6ab4c2e43f13aa18903d46e5aa6dd0ef9c5887140b4a5de2f6aa29b7ded9fa474197de82d8a374eec269a5a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
